name: flutter_hicons
description: Hicons is a collection of +2700 beautiful icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and usability.
version: 1.0.0
repository: https://github.com/stevenosse/flutter_hicons

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icon_font_generator: ^4.0.0

flutter:
  fonts:
    - family: Hicons
      fonts:
        - asset: fonts/hicons.otf

screenshots:
  - description: 'Hicons cover preview'
    path: cover.png